#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h" // Required for clock_get_hz

// This header is generated by CMake from our .pio file
#include "pd_sniffer.pio.h" 

// --- Configuration (FROM YOUR SCHEMATIC) ---
// The GPIO pin connected to the CC line comparator output
#define CC_PIN 28

// System clock speed (120 MHz)
// Note: We use clock_get_hz(clk_sys) for accuracy
// but define this for the divider calculation.
#define SYS_CLK_KHZ 120_000

// USB-PD BMC base clock rate (300 kHz)
#define PD_CLK_HZ 300_000

// Oversampling rate (8x)
#define OVERSAMPLE_RATE 8
#define SAMPLE_FREQ (PD_CLK_HZ * OVERSAMPLE_RATE) // 2.4 MHz

// DMA buffer size (in 32-bit words)
#define CAPTURE_BUF_SIZE (1024 * 4)

// --- Globals ---
PIO pio = pio0;
uint sm;
uint dma_chan;

// We make the buffer "dma_safe" by aligning it and placing it in a
// specific RAM section. This prevents bus contention.
__attribute__ ((aligned(4)))
uint32_t capture_buf[CAPTURE_BUF_SIZE];


// Main sniffer initialization
void sniffer_init() {
    // --- GPIO Setup ---
    // Initialize the CC_PIN (GP28) for PIO input
    // This is the output from your LMV358 comparator
    pio_gpio_init(pio, CC_PIN);
    // No pulls are needed; the comparator is driving this pin.
    
    // --- PIO Setup ---
    // Load the PIO program
    uint offset = pio_add_program(pio, &pd_sampler_program);

    // Find a free state machine
    sm = pio_claim_unused_sm(pio, true);

    // Calculate the clock divider for our sample rate
    float div = (float)clock_get_hz(clk_sys) / (float)SAMPLE_FREQ;

    // Initialize the PIO state machine
    pd_sampler_program_init(pio, sm, offset, CC_PIN, div);
    
    // --- DMA Setup ---
    // Get a free DMA channel
    dma_chan = dma_claim_unused_channel(true);
    dma_channel_config c = dma_channel_get_default_config(dma_chan);

    // Configure DMA
    channel_config_set_transfer_data_size(&c, DMA_SIZE_32); // 32-bit transfers
    channel_config_set_read_increment(&c, false);           // Read from same PIO FIFO address
    channel_config_set_write_increment(&c, true);           // Write to sequential buffer addresses
    channel_config_set_dreq(&c, pio_get_dreq(pio, sm, false)); // Triggered by PIO RX
    
    // Configure the DMA to loop back to the start of the buffer
    // when it reaches the end.
    channel_config_set_ring(&c, true, 14); // Ring write buffer (1<<14 = 16384 bytes = 4096 words)

    // Start DMA
    dma_channel_configure(
        dma_chan,
        &c,
        capture_buf,           // Write address (start of our buffer)
        &pio->rxf[sm],         // Read address (PIO RX FIFO)
        CAPTURE_BUF_SIZE,      // Number of transfers
        true                   // Start immediately
    );

    // --- Start ---
    // Start the PIO state machine
    pio_sm_set_enabled(pio, sm, true);
}

// Main loop to process and print the data
void sniffer_loop() {
    static uint32_t read_index = 0;

    // Get the DMA's current write position (as an index)
    uint32_t dma_write_index = dma_channel_get_write_addr(dma_chan) / 4;
    dma_write_index = (dma_write_index - ((uint32_t)capture_buf / 4)) % CAPTURE_BUF_SIZE;


    // Process all new data in the buffer
    while (read_index != dma_write_index) {
        
        // --- THIS IS OUR RAW DATA ---
        // For Milestone 1, we just print it as hex.
        // In Milestone 2, we'll replace this with our
        // BMC and 4b/5b decoder logic.
        printf("0x%08x\n", capture_buf[read_index]);
        
        // Move the read index forward, wrapping around
        read_index = (read_index + 1) % CAPTURE_BUF_SIZE;
    }

    // A small sleep prevents the USB serial from being
    // overwhelmed if there's no data.
    sleep_us(10); 
}

int main() {
    // Set system clock to 120 MHz
    set_sys_clock_khz(SYS_CLK_KHZ, true);

    // Initialize USB serial
    stdio_init_all();
    
    // Optional: wait for USB connection
    // while (!stdio_usb_connected()) { sleep_ms(100); }
    
    printf("RP2040 PD Sniffer Initializing...\n");
    printf("Clock: %lu Hz\n", clock_get_hz(clk_sys));
    printf("Sample Freq: %d Hz\n", SAMPLE_FREQ);
    printf("Capture Pin: GP%d\n", CC_PIN);

    // Initialize the PIO and DMA
    sniffer_init();
    
    printf("Sniffer running!\n");

    // --- Main Loop ---
    while (true) {
        sniffer_loop();
    }
}
