name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Create build directory and run CMake
        run: cmake -B build -S . -DNATIVE_BUILD=ON

      - name: Build and run tests
        run: |
          cmake --build build --parallel
          cd build
          ctest

  build_firmware:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential

      - name: Create build directory and run CMake
        run: cmake -B build -S .

      - name: Build firmware
        run: cmake --build build --parallel

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/src/sniffer/sniffer.uf2
            build/src/sink/sink.uf2
            build/src/test_firmware/pinger.uf2
            build/src/test_firmware/ponger.uf2
            build/src/test_firmware/source_emulator.uf2
            build/src/test_firmware/sink_tester.uf2
          tag_name: build-${{ github.sha }}
          name: Latest Build
          body: "Automatic build from commit ${{ github.sha }}"
          prerelease: true
