name: Cppcheck and Doxygen

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck gcc-arm-none-eabi cmake doxygen graphviz
    - name: Checkout pico-sdk
      run: git submodule update --init
    - name: Build and run cppcheck
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        cppcheck --project=compile_commands.json --enable=all --error-exitcode=1
    - name: Generate Doxygen documentation
      run: doxygen Doxyfile
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html
