name: Cppcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck gcc-arm-none-eabi cmake
    - name: Checkout pico-sdk
      run: git submodule update --init
    - name: Build and run cppcheck
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        cppcheck --project=compile_commands.json --enable=all --error-exitcode=1
